# Exception handling

## The try and except Blocks
- The order of `except` blocks matters. <br>If you define `except Exeption` above `except NameError` and NameError error occures, the **except Exception** block will be executed, and try-catch block will be closed. However Python requires the `except` block to be the last one in the list.  

```python
# Example 1
try:
    print(variable)
except Exception:
    print("")
except NameError:
    print("Variable is not defined") # This will be printed
except:           # Can only be the last value in try-catch
    print("Something went wrong") 

# Example 2
try:
    print(variable)
except Exception:
    print("Something went wrong") # This will be executed
except NameError:
    print("Variable is not defined")
except:
    print("Something went wrong")
```


## Defining Custom Exception Handlers

```python
atempts = 0

while True:
    try:
        input_var = input("Please enter a number: ")
        input_var = int(input_var)
        break
    
    except ValueError:
        attempts += 1

        if attempts < 3:
            print("Opps! That was not a valid number. Try again . . .")
        else:
            print("You really want to input a string! Fine we'll handle it")
            input_var = str(input_var)
            break
```

## The Exception Hierarchy




## Chaining except Blocks




## Exception Payloads




## Creating New Exceptions




## Assertions




## 






